Repository GlueOps/codespaces, pull requests merged in 2024-09, with the labels that each got.

#145 feat: adding packer for hetzner
  .github/workflows/packer-hetzner.yml
  hetzner.pkr.hcl
  os-setup.sh
Labels: enhancement, include-in-release-notes, minor

#146 feat: adding aws
  aws.pkr.hcl
  os-setup.sh
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 3, configuration changes

#147 fix: changing uid of vscode user to 1337 to be compatible with other …
  .devcontainer/Dockerfile
Labels: bug_fix

#148 feat: adding developer-setup.sh script to this repo and refactoring
  .github/workflows/packer-aws.yml
  README.md
  aws.pkr.hcl
  developer-setup.sh
  hetzner.pkr.hcl
  os-setup-finish.sh
  os-setup-start.sh
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 2

#155 feat: adding packer (1.11.2)
  .devcontainer/Dockerfile
Labels: enhancement, include-in-release-notes, minor, Review effort [1-5]: 2
