Repository GlueOps/codespaces, pull requests merged in 2024-10, with the labels that each got.

#157 major: make AWS AMI's publicly accessible across ALL aws accounts.
  aws.pkr.hcl
Labels: enhancement

#158 Feat/build hetzner in multi projects
  .github/workflows/packer-hetzner.yml
Labels: enhancement, include-in-release-notes, patch, minor, configuration changes, Review effort [1-5]: 2

#159 fix: zsh and refactor scripts
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/misc-configs/helm-repositories.yaml
  .devcontainer/tools/add-tools-to-shells.sh
  .devcontainer/tools/cordon-drain-nodes-older-than-minutes.sh
  .devcontainer/tools/create-ghcr-regcred.sh
  .devcontainer/tools/glueops-fetch-repos.sh
  .devcontainer/tools/run-gha.sh
  .devcontainer/tools/yolo.sh
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 3, bug_fix, Possible security concern

#161 chore(deps): update actions/checkout digest to eef6144
  .github/workflows/build_and_publish_devcontainer.yml
  .github/workflows/packer-aws.yml
  .github/workflows/packer-hetzner.yml
Labels: Review effort [1-5]: 1, auto-update, include-in-release-notes, patch, dependencies

#163 feat: add qemu builder github action
  .github/workflows/packer-qemu.yml
  qemu.pkr.hcl
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 3, configuration changes

#164 feat: restrict to codespaces runner
  .github/workflows/packer-qemu.yml
Labels: enhancement, include-in-release-notes, minor, configuration changes

#165 fix: add missing comma
  qemu.pkr.hcl
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, bug_fix

#170 fix: cordon-drain-nodes-older-than-minutes so that it actually waits …
  .devcontainer/tools/cordon-drain-nodes-older-than-minutes.sh
Labels: include-in-release-notes, patch, bug_fix, Review effort [1-5]: 2

#174 Feat/adding r2 bucket
  .github/workflows/packer-qemu.yml
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 2

#175 Feat/change to s3
  .github/workflows/packer-qemu.yml
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 2

#169 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#166 chore(deps): update actions/checkout digest to eef6144
  .github/workflows/packer-qemu.yml
Labels: Review effort [1-5]: 1, auto-update, include-in-release-notes, patch
