Repository GlueOps/codespaces, pull requests merged in 2025-03, with the labels that each got.

#251 fix: pinning devbox version to 0.13.0
  .devcontainer/Dockerfile
Labels: include-in-release-notes, patch, Review effort 1/5

#257 major: remove hetzner
  .github/workflows/packer-hetzner.yml
  hetzner.pkr.hcl
Labels: include-in-release-notes, major, Review effort 1/5

#258 feat: add python and node
  .devcontainer/devcontainer.json
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#259 fix: remove aws cli from qemu workflow
  .github/workflows/packer-qemu.yml
Labels: include-in-release-notes, patch, Review effort 1/5

#265 feat: adding qcow upload to AWS s3
  .github/workflows/packer-qemu.yml
Labels: enhancement, include-in-release-notes, minor, Review effort 2/5
