Repository GlueOps/codespaces, pull requests merged in 2025-05, with the labels that each got.

#300 major: removing gcloud SDK (again)
  .devcontainer/Dockerfile
Labels: include-in-release-notes, major, Review effort 2/5

#289 chore: remove hetzner from docs and add QA/Testing steps to docs
  README.md
Labels: include-in-release-notes, patch, Review effort 1/5

#302 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  PRCHECKLIST
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#305 fix: update github actions to fetch full repo history
  .github/workflows/packer-aws.yml
  .github/workflows/packer-qemu.yml
Labels: include-in-release-notes, patch, Review effort 1/5

#306 fix: debugging gha
  .github/workflows/packer-aws.yml
  .github/workflows/packer-qemu.yml
Labels: include-in-release-notes, patch, Review effort 1/5

#307 feat: update runs-on to use codespace hosted runner for faster builds
  .github/workflows/build_and_publish_devcontainer.yml
Labels: enhancement, include-in-release-notes, minor

#308 Fix/workflows
  .github/workflows/build_and_publish_devcontainer.yml
  .github/workflows/packer-aws.yml
  .github/workflows/packer-qemu.yml
Labels: enhancement, include-in-release-notes, patch, minor, Review effort 2/5

#310 fix: revert runs-on node for container image build
  .github/workflows/build_and_publish_devcontainer.yml
Labels: include-in-release-notes, patch, Review effort 1/5

#311 feat: change dev command to default to using builtin/cached codespaces tag
  .github/workflows/build_and_publish_devcontainer.yml
  README.md
  developer-setup.sh
Labels: enhancement, include-in-release-notes, patch, minor, Review effort 2/5
