Repository GlueOps/codespaces, pull requests merged in 2025-04, with the labels that each got.

#271 Revert "chore(deps): update dependency derailed/k9s to v0.40.11"
  .devcontainer/Dockerfile
Labels: include-in-release-notes, Review effort 1/5

#273 major: remove image cache api in workflow
  .github/workflows/packer-qemu.yml
Labels: include-in-release-notes, major, Review effort 1/5

#276 feat: set dev command to use provisioner api
  developer-setup.sh
Labels: enhancement, include-in-release-notes, patch, minor, Review effort 2/5

#281 feat: adding warning for no backups
  .devcontainer/Dockerfile
Labels: enhancement, include-in-release-notes, patch, minor, Review effort 1/5

#282 feat: adding a dev shortcut to use when logging in as root instead of vscode user
  developer-setup.sh
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#264 fix: change hardcoded password to rand generate a temp one
  .github/workflows/packer-qemu.yml
  qemu.pkr.hcl
Labels: include-in-release-notes, patch, Review effort 2/5

#285 feat: improve codespace persistence
  developer-setup.sh
Labels: enhancement, include-in-release-notes, patch, minor, major, Review effort 3/5

#287 major: migrating log4brains from docker to npm cli as the docker based approach made it difficult to edit the docs
  .devcontainer/tools/log4brains.sh
Labels: include-in-release-notes, major, Review effort 1/5

#284 chore: Update README.md with new release steps
  README.md
Labels: include-in-release-notes, patch, Review effort 1/5

#291 feat: when launching code tunnel it switches the tmux session to read only which should prevent interruptions like ctrl + c from the user
  developer-setup.sh
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#292 feat: update MOTD as regardless of the user it will switch them to vs…
  developer-setup.sh
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5
